# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the project
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (not required for stdio MCP servers)

# Start the MCP server
CMD ["node", "build/index.js"]
